### ISSUE TITLE
Uncaught exception 

### ISSUE THREAD

**Issue by mussumSantos** [coinbase/coinbase-php#164]
Hello, I'm trying to catch the exceptions and print the errors, but I couldn't do. Anybody may help me?

(Really I don't have that much!! The trouble is catch the exception)

The log:
```
Fatal error:  Uncaught exception 'GuzzleHttp\Exception\ClientException' with message 'Client error: `POST https://api.coinbase.com/v2/accounts/accountID/transactions` resulted in a `422 Unprocessable Entity` response:
{"errors":[{"id":"validation_error","message":"You don't have that much.","field":"base"}]}
' in /home/pegaso/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php:107
Stack trace:
#0 /home/pegaso/vendor/guzzlehttp/guzzle/src/Middleware.php(65): GuzzleHttp\Exception\RequestException::create(Object(GuzzleHttp\Psr7\Request), Object(GuzzleHttp\Psr7\Response))
#1 /home/pegaso/vendor/guzzlehttp/promises/src/Promise.php(203): GuzzleHttp\Middleware::GuzzleHttp\{closure}(Object(GuzzleHttp\Psr7\Response))
#2 /home/pegaso/vendor/guzzlehttp/promises/src/Promise.php(156): GuzzleHttp\Promise\Promise::callHandler(1, Object(GuzzleHttp\Psr7\Response), Array)
#3 /home/pegaso/vendor/guzzlehttp/promises/src/TaskQueue.php(61): GuzzleHttp\Promise\Promise::GuzzleHttp\Promise\{closure}()
 in /home/pegaso/general/php_code/coinbase/src/Exception/HttpException.php on line 37
```

My code:
```php
require_once('/home/pegaso/vendor/autoload.php');
use Coinbase\Wallet\Client;
use Coinbase\Wallet\Configuration;
use Coinbase\Wallet\Resource\Address;
use Coinbase\Wallet\Resource\Account;
use Coinbase\Wallet\Resource\Resource;
use Coinbase\Wallet\Resource\ResourceCollection;
use Coinbase\Wallet\Enum\LitecoinAddress;
use Coinbase\Wallet\Enum\CurrencyCode;
use Coinbase\Wallet\Resource\Transaction;
use Coinbase\Wallet\Value\Money;
use Coinbase\Wallet\Exception;
use GuzzleHttp\Exception\ClientException;
use GuzzleHttp\Exception\RequestException;

$configuration = Configuration::apiKey($apiKey, $apiSecret);
$client = Client::create($configuration);
$account = Account::reference('accountID');
$transaction = Transaction::send([
  'to'               => new Address('Litecoin Address'),
  'amount'           => new Money(7, CurrencyCode::LTC),	
  'description'      => 'My first litecoin!'
  ]);

try {
  $client->createAccountTransaction($account, $transaction);
} 
catch (ClientException $e) {
  echo 'Caught response: ' . $e->getResponse()->getStatusCode();
}
```

**Comment by sds** [comment]
Hey @mussumSantos,

Do not attempt to catch a Guzzle HTTP exception directly, as it is wrapped by a `Coinbase\Wallet\Exception\HttpException`. Instead you should have:

```php
use Coinbase\Wallet\Exception\HttpException;
```
...and change your `catch` statement to:
```php
catch (HttpException $e) {
```

Hope that helps.
