### ISSUE TITLE
Status code 409

### ISSUE THREAD

**Issue by gregtampa** [coinbase/coinbase-php#47]
PHP Fatal error:  Uncaught exception 'Coinbase_ApiException' with message 'Status code 409'

409 Conflict

The request could not be completed due to a conflict with the current state of the resource. This code is only allowed in situations where it is expected that the user might be able to resolve the conflict and resubmit the request. The response body SHOULD include enough

information for the user to recognize the source of the conflict. Ideally, the response entity would include enough information for the user or user agent to fix the problem; however, that might not be possible and is not required.

Conflicts are most likely to occur in response to a PUT request. For example, if versioning were being used and the entity being PUT included changes to a resource which conflict with those made by an earlier (third-party) request, the server might use the 409 response to indicate that it can't complete the request. In this case, the response entity would likely contain a list of the differences between the two versions in a format defined by the response Content-Type.

PHP Fatal error:  Uncaught exception 'Coinbase_ApiException' with message 'Status code 409' in /var/www/html/api/coinbase-php/lib/Coinbase/Requestor.php:22\nStack trace:\n#0 /var/www/html/api/coinbase-php/lib/Coinbase/Rpc.php(95): Coinbase_Requestor->doCurlRequest(Resource id #1)\n#1 /var/www/html/api/coinbase-php/lib/Coinbase/Coinbase.php(64): Coinbase_Rpc->request('GET', 'accounts/5588a7...', Array)\n#2 /var/www/html/api/coinbase-php/lib/Coinbase/Coinbase.php(104): Coinbase->get('accounts/5588a7...', Array)\n#3 /var/www/html/api/coinbase-php/functions.php(149): Coinbase->getbtcaddress('5588a7bc9e97f8c...')\n#4 /var/www/html/api/coinbase-php/functions.php(22): getAllAddresses(2)\n#5 /var/www/html/header.php(1): require_once('/var/www/html/a...')\n#6 /var/www/html/index.php(5): include('/var/www/html/h...')\n#7 {main}\n  thrown in /var/www/html/api/coinbase-php/lib/Coinbase/Requestor.php on line 22

**Comment by gregtampa** [comment]
looks like coinbase.com is down:
Error 1001 Ray ID: 201e6c511bda1804 • 2015-07-06 21:32:35 UTC
DNS resolution error
What happened?
You've requested a page on a website (coinbase.com) that is on the CloudFlare network. CloudFlare is currently unable to resolve your requested domain (coinbase.com). There are two potential causes of this:
Most likely: if the owner just signed up for CloudFlare it can take a few minutes for the website's information to be distributed to our global network.
Less likely: something is wrong with this site's configuration. Usually this happens when accounts have been signed up with a partner organization (e.g., a hosting provider) and the provider's DNS fails.
